### ISSUE TITLE
workshop branch; Could not find artifact error-prone-support:pom:0.14.1-SNAPSHOT

### ISSUE THREAD

**Issue by tubbynl** [PicnicSupermarket/error-prone-support#1124]
### Describe the bug

As part of the preparation for the workshop i was cloning this repo and setting up versions and stuff. 

Requirements (Important: make sure you have this ready on your laptop before the start of the workshop):
- Your favourite IDE
- Java 17
- Link to project: https://github.com/PicnicSupermarket/error-prone-support/.
- Clone the repository to your laptop.
- Checkout the `workshop` branch.
- Perform a `mvn clean install` in the root of the repository and get a successful build.
- If you encounter any problems, create an issue in Error Prone Support or open a discussion in the repository.

### Minimal Reproducible Example

* Checkout the `workshop` branch. 244ac55a011425845004472e431082634076c4ee
*  Perform a `mvn clean install` in the root of the repository

```
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: 
The following artifacts could not be resolved: 
tech.picnic.error-prone-support:error-prone-support:pom:0.14.1-SNAPSHOT (absent): 
```

### Setup

```
mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: ~/.sdkman/candidates/maven/3.9.6
Java version: 17.0.9, vendor: Eclipse Adoptium, runtime: ~/.sdkman/candidates/java/17.0.9-tem
Default locale: nl_NL, platform encoding: UTF-8
OS name: "mac os x", version: "14.4.1", arch: "aarch64", family: "mac"
```

### Additional context

This will probably be something other people also run in to for the meetup https://www.meetup.com/codelabjug/events/299169758/

**Comment by TomKeur** [comment]
It seems this have been fixed 👍

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Picnic :: Error Prone Support 0.16.2-SNAPSHOT:
[INFO]
[INFO] Picnic :: Error Prone Support ...................... SUCCESS [  2.625 s]
[INFO] Picnic :: Error Prone Support :: Documentation Support SUCCESS [  6.415 s]
[INFO] Picnic :: Error Prone Support :: Utils ............. SUCCESS [  3.968 s]
[INFO] Picnic :: Error Prone Support :: Refaster Support .. SUCCESS [  4.220 s]
[INFO] Picnic :: Error Prone Support :: Refaster Compiler . SUCCESS [  1.147 s]
[INFO] Picnic :: Error Prone Support :: Refaster Runner ... SUCCESS [  3.785 s]
[INFO] Picnic :: Error Prone Support :: Refaster Test Support SUCCESS [  3.573 s]
[INFO] Picnic :: Error Prone Support :: Contrib ........... SUCCESS [ 19.641 s]
[INFO] Picnic :: Error Prone Support :: Experimental ...... SUCCESS [  3.345 s]
[INFO] Picnic :: Error Prone Support :: Guidelines ........ SUCCESS [  3.383 s]
[INFO] Picnic :: Error Prone Support :: Workshop .......... SUCCESS [  2.645 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  54.854 s
[INFO] Finished at: 2024-04-05T12:20:31+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by rickie** [comment]
Hi @tubbynl, thanks for reporting the issue! 

Indeed as @TomKeur mentioned by now this is fixed. [Here](https://github.com/PicnicSupermarket/error-prone-support/commit/fcd708e00f011c7480483ffec11f9be19336a760#diff-d891264cc5da3c816bb10e1448c04d9b18bcfa5652e556e73740f0f2b6126fc1L8-R8) we were still referencing an old version because of me making a mistake with rebasing.
