### ISSUE TITLE
Drop redundant `Matchers.{allOf,anyOf}` containing a single `Matcher`

### ISSUE THREAD

**Issue by oxkitsune** [PicnicSupermarket/error-prone-support#340]
### Problem
Declaring a `Matcher` using `Matchers.{allOf,anyOf}(Matcher...)` containing  just a single `Matcher`, is redundant.

### Description of the proposed new feature

- [ ] Support a stylistic preference.
- [x] Avoid a common gotcha, or potential problem.

We can rewrite
```java
allOf(annotations(AT_LEAST_ONE, isType("org.junit.jupiter.params.provider.MethodSource")));
anyOf(annotations(AT_LEAST_ONE, isType("org.junit.jupiter.params.provider.MethodSource")));
```

to:
```java
annotations(AT_LEAST_ONE, isType("org.junit.jupiter.params.provider.MethodSource"));
annotations(AT_LEAST_ONE, isType("org.junit.jupiter.params.provider.MethodSource"));
```

### Considerations

This should support the method overloads `Matchers.{allOf,anyOf}(Iterable<? extends Matcher>)`.

### Participation

This is a nice opportunity to get your hands dirty with `BugChecker`s :rocket:

**Comment by rickie** [comment]
A related example of what this check would flag: https://github.com/PicnicSupermarket/error-prone-support/pull/335#discussion_r1016351033.

**Comment by EvgheniiShipilov** [comment]
I'd like to pick this one up. Anything I should be aware of?

**Comment by rickie** [comment]
> I'd like to pick this one up. 

Nice! 

Ah I think you found the most similar `RefasterAnyOfUsage` check already. Another one would be the `IdentityConversion` check. As that check also flags enclosing method invocations that can be dropped. 

Well, actually now that I'm thinking of that and looking into the tests of that check; maybe this would be as simple as adding these exact methods to `IS_CONVERSION_METHOD` 🤔. 

(Not sure if the naming would still be correct for `IS_CONVERSION_METHOD` but that's another concern).

Currently not able to try it out, but might be later / tomorrow.

**Comment by rickie** [comment]
Sorry, a little later than expected, but I tried it out.

Indeed, we can use the `IS_CONVERSION_METHOD` and the `IdentityConversion` check to solve this problem. 

With this information, do you have enough context to proceed with opening a PR 😉?

**Comment by EvgheniiShipilov** [comment]
I think this should be enough, thanks for looking into it!
