### ISSUE TITLE
Simplify Reactor `switchIfEmpty(Mono.just(...))` using `defaultIfEmpty`

### ISSUE THREAD

**Issue by EnricSala** [PicnicSupermarket/error-prone-support#363]
### Problem

Specifying default behavior in a Reactor publisher can be written like `switchIfEmpty(Mono.just(42))` or `defaultIfEmpty(42)`.

The behavior is identical, but the latter is more concise and may have slight performance benefits due to reduced overhead.

### Description of the proposed new feature

- [x] Support a stylistic preference.
- [ ] Avoid a common gotcha, or potential problem.

I would like to rewrite the following code:
```java
Mono<Integer> mono = ...;
return mono.switchIfEmpty(Mono.just(42));
```
to:
```java
Mono<Integer> mono = ...;
return mono.defaultIfEmpty(42);
```

### Considerations

- The rewrite operation is applicable for both `Mono` and `Flux`.
- This rewrite is only suitable when the default is a `{Mono|Flux}.just(...)`. Cases like `Mono.fromSupplier` cannot be rewritten because they would lose the lazy-evaluation behavior.
- It could be possible to rewrite also cases like `switchIfEmpty(Mono.empty())`, in which case the `switchIfEmpty` operator can simply be dropped.

### Participation

- [ ] I am willing to submit a pull request to implement this improvement.

**Comment by giall** [comment]
Opened a PR: https://github.com/PicnicSupermarket/error-prone-support/pull/370. The third point in consideration seems to already be covered by the `MonoSwitchIfEmptyOfEmptyPublisher` rule.
