### ISSUE TITLE
Rewrite `Optional.ofNullable(A).orElse(B)` to `requireNonNullElse(A, B)`

### ISSUE THREAD

**Issue by EnricSala** [PicnicSupermarket/error-prone-support#364]
### Problem

Sometimes a nullable variable can be wrapped in an `Optional` simply to perform a null-or-else check.

In such cases it's simpler to use `requireNonNullElse` or `requireNonNullElseGet` from `java.util.Objects`.

### Description of the proposed new feature

- [x] Support a stylistic preference.
- [ ] Avoid a common gotcha, or potential problem.

I would like to rewrite the following code:
```java
Optional.ofNullable(A).orElse(B);
Optional.ofNullable(A).orElseGet(() -> getB());
```

to:
```java
requireNonNullElse(A, B);
requireNonNullElseGet(A, () -> getB());
```

### Considerations

Could also consider the case `Optional.of(A).orElse(B)` which can be rewritten as just `A`, and similar for `orElseGet`. 
**EDIT**: actually, `Optional.of` would already throw an exception if `A` was `null`, while replacing with just `A` could propagate the `null` further, so it should be replaced with `requireNonNull(A)`.

### Participation

- [ ] I am willing to submit a pull request to implement this improvement.

**Comment by Stephan202** [comment]
Nice one. The first `Optional.ofNullable` case can be added to [this existing rule](https://github.com/PicnicSupermarket/error-prone-support/blob/b2e15607c1990c3c3d65b1588d1bb3bd49824dac/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java#L46-L60), provided that the Javadoc is tweaked a bit. Note that the same caveat around `B` possibly being `null` applies. (We might be able to partially mitigate this by applying a custom `@Matches` annotation :thinking:.)

**Comment by Stephan202** [comment]
NB: I see I had this same rule in my private TODO list, followed by:
* `requireNonNullElse(map.get(k), defaultValue)` -> `map.getOrDefault(k, defaultValue)`

**Comment by Stephan202** [comment]
Another observation: the `Optional.of` rule has a reactive analog; from my TODO list:
* `Mono.just(elem).defaultIfEmpty(elem2)` -> `Mono.just(elem)`
