### ISSUE TITLE
Refaster rules that encourage filtering before sorting

### ISSUE THREAD

**Issue by Stephan202** [PicnicSupermarket/error-prone-support#386]
### Problem

Given a stream of elements that must be filtered and sorted, it is generally more efficient to do the former first, so that the subsequent sorting step involves fewer elements. This applies to `Stream`, `IntStream`, `LongStream`, `DoubleStream` and `Flux` types.

### Description of the proposed new feature

- [ ] Support a stylistic preference.
- [x] Avoid a common gotcha, or potential problem.

Rewrite:
```
stream.sorted().filter(pred)
```
to:
```
stream.filter(pred).sorted()
```

Do the same for the other types mentioned above, as well as `Comparator`-accepting sort method overloads.

### Considerations

One nice advantage of the proposed rewrite rules is that [these simplifications](https://github.com/PicnicSupermarket/error-prone-support/blob/5afa7e1878453f97996ed73c36847844e07074cb/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java#L222-L2460) might subsequently kick in.

**Comment by CoolTomatos** [comment]
I would like to pick this one up for the cute new Christmax edition sticker haha.
