### ISSUE TITLE
Rewrite `collection.stream().forEach(consumer)` to `collection.forEach(consumer)`

### ISSUE THREAD

**Issue by Stephan202** [PicnicSupermarket/error-prone-support#387]
### Problem

Summary says it; this is a good candidate for a Refaster rule.

### Description of the proposed new feature

- [x] Support a stylistic preference.
- [ ] Avoid a common gotcha, or potential problem.

Use Refaster to rewrite code of the form:
```java
collection.stream().forEach(consumer);
```
to
```java
collection.forEach(consumer);
```

### Considerations

_In theory_ this rewrite rule could change the code's semantics, but this is unlikely in practice.

**Comment by amestoyg** [comment]
I'd like to pick this one up.
