### ISSUE TITLE
Rewrite `requireNonNullElse(map.get(k), defaultValue)` -> `map.getOrDefault(k, defaultValue)`

### ISSUE THREAD

**Issue by rickie** [PicnicSupermarket/error-prone-support#431]
### Problem

As @Stephan202 mentioned in https://github.com/PicnicSupermarket/error-prone-support/issues/364, we can create a Refaster rule that rewrites the following:

`requireNonNullElse(map.get(k), defaultValue)` -> `map.getOrDefault(k, defaultValue)`.  

### Description of the proposed new feature

- [x] Support a stylistic preference.
- [ ] Avoid a common gotcha, or potential problem.
- [ ] Improve performance.

I would like to rewrite the following code:
```java
Map<Integer, Integer> map = Map.of(1, 2); 
Integer integer = requireNonNullElse(map.get(1), 3);
```

to:
```java
Map<Integer, Integer> map = Map.of(1, 2);
Integer integer = map.getOrDefault(1, 3);
```

**Comment by benhalasi** [comment]
I've made a pull request with the needed refaster rules.

Would have tried to apply them too but I wasn't able to use `./apply-error-prone-suggestions.sh` as I couldn't get a hold of some maven artifacts.

Did I misunderstand something about the rewriting or that script?

The missing artifacts are:
- com.github.PicnicSupermarket.error-prone:error_prone_annotation:jar:v2.17.0-picnic-1
- com.github.PicnicSupermarket.error-prone:error_prone_check_api:jar:v2.17.0-picnic-1
- com.github.PicnicSupermarket.error-prone:error_prone_core:jar:v2.17.0-picnic-1
- com.github.PicnicSupermarket.error-prone:error_prone_test_helpers:jar:v2.17.0-picnic-1

I found 2020 versions of them in maven central if that's relevant.

**Comment by Stephan202** [comment]
@benhalasi ah, you found a bug! :bug: We use [`settings.xml`](https://github.com/PicnicSupermarket/error-prone-support/blob/becfcb5374e7f5f1fed13fe1477fb300c2014b29/settings.xml) to download some artifacts from Jitpack, but in this repo that file is only actually used by [GitHub Actions](https://github.com/PicnicSupermarket/error-prone-support/blob/becfcb5374e7f5f1fed13fe1477fb300c2014b29/.github/workflows/build.yaml#L50); the scripts for local execution don't specify it. I'll propose a fix later today. (I want to make sure that the script makes no assumptions about execution location.)

(The reason that so far this issue went unnoticed, is that without a `settings.xml` override the file in `$M2_HOME`  is used, which for Picnic developers points to our company Nexus deployment, which proxies to Jitpack.)

**Comment by Stephan202** [comment]
I filed #441 for the `apply-error-prone-suggestions.sh` issue :)
