### ISSUE TITLE
convert import xxx.*; to single imports

### ISSUE THREAD

**Issue by Jiehong** [PicnicSupermarket/error-prone-support#893]
In the google format guide, wildcard imports aren't allowed.

It would be nice if a refaster rule could convert * imports to single imports.

However, it's not immediately clear to me if a refaster template could even handle such a case.

What do you think?

**Comment by rickie** [comment]
Hi @Jiehong, thanks for taking the time to open an issue in Error Prone Support.

What you are describing is something that exists in the original [Error Prone repository](https://github.com/google/error-prone) 😄 . 
Here is a link to the documentation of the Error Prone check: https://errorprone.info/bugpattern/WildcardImport. 

Refaster only works on expressions and statements so is not ideal for this use case.

**Comment by rickie** [comment]
In this repository we have some improvements for the reporting of matches with Refaster (see [here](https://github.com/PicnicSupermarket/error-prone-support/blob/master/refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java#L118-L139)). 

In our README there is a [setup section](https://github.com/PicnicSupermarket/error-prone-support/#-getting-started) that shows you how you can configure Error Prone and Refaster together. Did you try to use this setup? 

---
About the failing fix you mentioned. In a local demo repository I added the following code:
```
import java.util.*;

public final class HelloWorld {
  private HelloWorld() {}

  public static void main(String[] args) {
    Queue<String> queue = null;
    HashMap<String,String> map = null;

    System.out.println("queue" + queue + map);
  }
}
```
Running patch on this results in the following import section:
```
import java.util.HashMap;
import java.util.Queue;
```
If this is not working for you, I'd suggest to create a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.) and file a bug report in [google/error-prone](https://github.com/google/error-prone) 😄.

**Comment by rickie** [comment]
Hi, feel free to post something if you have further questions or an update. For now I'll close the issue 🙂.
